/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.BANANDAO;
import DAO.CHITIETHOADONDAO;
import DAO.HOADONDAO;
import DAO.MonAnDAO;
import DAO.NhanVienDAO;
import DAO.PhieuGoiMonDAO;
import POJO.BanAn;
import POJO.HoaDon;
import POJO.MonAn;
import POJO.NhanVien;
import POJO.PhieuGoiMon;
import java.awt.Color;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.awt.Cursor;
import java.awt.Dimension;
import static java.awt.Frame.HAND_CURSOR;
import java.awt.GridLayout;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BoxLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thuong Nguyen
 */
public class datban1 extends javax.swing.JFrame {

    /**
     * Creates new form datban
     */
    PhieuGoiMonDAO phieuGoiMonDao = new PhieuGoiMonDAO();
    DefaultTableModel tableModel = new DefaultTableModel();
    JButton buttonTrangThai;
    int tongTien = 0;
    String maBan = "";
    int tienNhan = 0;
    String maNV = "";
    public datban1() {
        initComponents();
        this.setLocationRelativeTo(null); 
        this.setTitle("Quản lý nhà hàng");

        String[] header = {"Mã món ăn","Mã nhân viên", "Tên món", "Số lượng", "Thành tiền"};
        this.tableModel.setColumnIdentifiers(header);
        this.table_monAn.setModel(tableModel); 
        this.table_monAn.getColumnModel().getColumn(0).setMinWidth(0);
        this.table_monAn.getColumnModel().getColumn(0).setMaxWidth(0);

        //loadConnect(); 
        loadNhanVien();
        loadCboMonAn();
        loadBanAn();
        loadImageMonAn(); 
        loadIcon();
        loadTime();
        loadEnable(false);
        loadCursor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        datban = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbo_monAn = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_SoLuong = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_monAn = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_tienNhanCuaKhach = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btn_thanhToan = new javax.swing.JButton();
        label_donGiaMonAn = new javax.swing.JLabel();
        label_thanhTien = new javax.swing.JLabel();
        label_date = new javax.swing.JLabel();
        label_time = new javax.swing.JLabel();
        label_tongTien = new javax.swing.JLabel();
        label_tienThua = new javax.swing.JLabel();
        txt_image = new javax.swing.JLabel();
        label_tenBan = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        label_tenNhanVien = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        panel_datBan = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        label_chuaCoKhach = new javax.swing.JLabel();
        label_daCoKhach = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setLayout(new java.awt.CardLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setText("ĐẶT BÀN");

        cbo_monAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_monAnActionPerformed(evt);
            }
        });

        jLabel11.setText("Giá: ");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Số lượng");

        txt_SoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_SoLuongKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_SoLuongKeyTyped(evt);
            }
        });

        jLabel14.setText("Thành Tiền: ");

        table_monAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã món ăn", "Tên món", "Số lượng", "Thành tiền"
            }
        ));
        table_monAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_monAnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_monAn);

        jLabel15.setText("Tổng Tiền: ");

        jLabel16.setText("Tiền Nhận Của Khách: ");

        jLabel17.setText("Tiền Thừa: ");

        txt_tienNhanCuaKhach.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_tienNhanCuaKhach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_tienNhanCuaKhachKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_tienNhanCuaKhachKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Họ Và Tên Nhân Viên:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Ngày:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("Thời Gian:");

        btn_thanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thanhToanActionPerformed(evt);
            }
        });

        label_donGiaMonAn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_donGiaMonAn.setText("0 VNĐ");

        label_thanhTien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_thanhTien.setText("0 VNĐ");

        label_date.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_date.setText("09/12/2022");

        label_time.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_time.setText("09:48:43");

        label_tongTien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_tongTien.setText("0 VNĐ");

        label_tienThua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_tienThua.setText("0 VNĐ");

        txt_image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label_tenBan.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N

        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(30, 30, 30)
                                    .addComponent(label_donGiaMonAn))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(cbo_monAn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txt_image, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(33, 33, 33)
                                .addComponent(label_thanhTien))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_tienThua)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_tongTien)
                                    .addComponent(txt_tienNhanCuaKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_thanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel20)
                        .addComponent(label_time)
                        .addComponent(label_date, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel18)
                        .addComponent(label_tenBan, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_tenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_tenBan, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cbo_monAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_image, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_donGiaMonAn)
                                    .addComponent(jLabel11)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(label_thanhTien))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(label_tenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(label_date)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(label_time)))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_thanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(label_tongTien))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(txt_tienNhanCuaKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(label_tienThua))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        panel_datBan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panel_datBanLayout = new javax.swing.GroupLayout(panel_datBan);
        panel_datBan.setLayout(panel_datBanLayout);
        panel_datBanLayout.setHorizontalGroup(
            panel_datBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_datBanLayout.setVerticalGroup(
            panel_datBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Chưa có khách");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Đã có khách");

        label_chuaCoKhach.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_datBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_chuaCoKhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_daCoKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel22)))
                .addGap(36, 36, 36))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_daCoKhach, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(label_chuaCoKhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(46, 46, 46)
                .addComponent(panel_datBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout datbanLayout = new javax.swing.GroupLayout(datban);
        datban.setLayout(datbanLayout);
        datbanLayout.setHorizontalGroup(
            datbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datbanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(datbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datbanLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(datbanLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        datbanLayout.setVerticalGroup(
            datbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datbanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datbanLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(datbanLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel5.add(datban, "card3");

        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(946, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_monAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_monAnActionPerformed
        // TODO add your handling code here:
        if (this.checkEnableBtnAdd()) {
            this.btn_add.setEnabled(true);
        }
        loadImageMonAn();
        capNhatThanhTien();
    }//GEN-LAST:event_cbo_monAnActionPerformed

    private void txt_SoLuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SoLuongKeyReleased
        // TODO add your handling code here:
        if (cbo_monAn.getSelectedIndex() == -1) {
            return;
        }
        if (this.checkEnableBtnAdd()) {
            this.btn_add.setEnabled(true);
        }
        capNhatThanhTien();
    }//GEN-LAST:event_txt_SoLuongKeyReleased

    private void txt_SoLuongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SoLuongKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar()))
        evt.consume();
    }//GEN-LAST:event_txt_SoLuongKeyTyped

    private void table_monAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_monAnMouseClicked
        try {
            // TODO add your handling code here:
            this.btn_delete.setEnabled(true); 
            int rowSelect = this.table_monAn.getSelectedRow();
            String maMonAn = this.table_monAn.getValueAt(rowSelect, 0).toString();
            MonAnDAO monAnDao = new MonAnDAO();
            //NHẬN 1 MÓN ĂN TỪ MÃ
            MonAn x = monAnDao.getOneMonAnByMaMonAn(maMonAn);
            //EDIT ẢNH
            BufferedImage bufferedImage = ImageIO.read(new File("src/Image/" + x.getHinh()));
            Image image = bufferedImage.getScaledInstance(this.txt_image.getWidth() - 10, this.txt_image.getHeight() - 10, 1);
            this.txt_image.setIcon(new ImageIcon(image));
            //SET SELECTED COMBOBOX CHO MÓN ĂN ĐUỌC CHỌN
            int kq = monAnDao.getIndexMonAn(maMonAn);
            this.cbo_monAn.setSelectedIndex(kq);
            String manv = table_monAn.getValueAt(rowSelect, 1).toString().trim();
            String tenNV = NhanVienDAO.getTenNV(manv);
            label_tenNhanVien.setText(tenNV);
        } catch (IOException ex) {
            Logger.getLogger(datban1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_table_monAnMouseClicked

    private void txt_tienNhanCuaKhachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tienNhanCuaKhachKeyReleased
        // TODO add your handling code here:
        if ((!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) || this.tongTien == 0) {
            evt.consume();
        } else {
            //LUU LAI TIEN NHAN(FORMAT THEO CODE) VAO BIẾN TIEN NHAN
            if (!Character.isISOControl(evt.getKeyChar())) {
                this.tienNhan = Integer.parseInt(String.valueOf(this.tienNhan) + evt.getKeyChar());
            } else {
                this.tienNhan /= 10;
            }
            evt.consume();
            //XU LY TIEN THUA
            int tienThua = this.tienNhan - this.tongTien;
            this.label_tienThua.setText(NumberFormat.getInstance().format(tienThua) + " VNĐ");
            //NumberFormat.getInstance().parse(this.txt_tienNhanCuaKhach.getText()) (CHUYỂN ĐỔI STRING PHÂN TÁCH HÀNG NGÀN VỀ SỐ)
            //FOTMAT TIEN NHAN
            this.txt_tienNhanCuaKhach.setText(NumberFormat.getInstance().format(this.tienNhan));

            //CHECK ENABLE BTN THANH TOAN
            if (this.checkEnableBtnPay()) {
                this.btn_thanhToan.setEnabled(true);
            }
        }
    }//GEN-LAST:event_txt_tienNhanCuaKhachKeyReleased

    private void txt_tienNhanCuaKhachKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tienNhanCuaKhachKeyTyped
        // TODO add your handling code here:
        if (this.table_monAn.getRowCount() < 1)
        evt.consume();
    }//GEN-LAST:event_txt_tienNhanCuaKhachKeyTyped

    private void btn_thanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thanhToanActionPerformed
        try {
            // TODO add your handling code here:
            PhieuGoiMonDAO phieuGoiMonDAO = new PhieuGoiMonDAO();
            //TU CHOI THANH TOÁN NEU TIEN THUA AM
            int tienThua = Integer.parseInt(NumberFormat.getInstance().parse(this.label_tienThua.getText()) + "");
            if (tienThua < 0) {
                JOptionPane.showMessageDialog(this, "Tiền nhận không đủ", "Thông báo", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (ParseException ex) {
            Logger.getLogger(datban1.class.getName()).log(Level.SEVERE, null, ex);
        }

        //CAP NHAT TIEN THANH 0 DONG
        txt_tienNhanCuaKhach.setText("0");
        label_tienThua.setText("0 VNĐ");
        this.tienNhan = 0;

        //ĐỔI TRẠNG THÁI BÀN
        this.changeStateTable(false);

        //LƯU HÓA ĐƠN
        try {
            //TẠO HÓA DON VÀ INSERT VAO BẢNG HOA DON
            HOADONDAO hoaDonDao = new HOADONDAO();
            HoaDon hoaDon = new HoaDon();
            hoaDon.setTongTien(tongTien);
            hoaDon.setMaNhanVien(this.maNV);
            
            String tennv = label_tenNhanVien.getText();
            String maNV = NhanVienDAO.getNhanVienByMa(tennv);
            
            boolean n = hoaDonDao.themHoaDon(hoaDon, maNV);
            if (n) {
                //NHẬN MÃ HOA DON VỪA TẠO
                String maHoaDon = getLastInsertMaHoaDon();
                //INSERT BẢNG CHI TIET HOA DON
                createChiTietHoaDon(maHoaDon);
                //Xoa phieu goi
                phieuGoiMonDao.deleteAllPhieuGoiMonByMaBan(this.maBan);
                JOptionPane.showMessageDialog(this, "Thanh toán thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadTableMonAn();
            } else {
                JOptionPane.showMessageDialog(this, "Thanh toán thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (HeadlessException | NumberFormatException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Thanh toán thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_thanhToanActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:

        //CHECK SỐ LƯỢNG ĐỒ ĂN COI CÒN ĐỂ GỌI KO
        if (this.cbo_monAn.getSelectedIndex() == -1) {
            return;
        }
        MonAnDAO monAnDao = new MonAnDAO();
        MonAn monAn = (MonAn) this.cbo_monAn.getSelectedItem();
        if (monAnDao.getSoLuongByMaMonAn(monAn.getMaMonAn() + "") < Integer.parseInt(txt_SoLuong.getText())) {
            JOptionPane.showMessageDialog(this, "Số lượng cho món ăn này không đủ !!!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //THAY ĐỔI TRẠNG THÁI BÀN THÀNH ĐÃ CÓ KHÁCH
        this.changeStateTable(true); 

        if (this.findFootQuantityInPhieuGoiMon() != -1) {
            int n = JOptionPane.showConfirmDialog(this, "Món này đã được gọi, bạn có muốn thêm số lượng?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (n == JOptionPane.YES_OPTION) {
                this.updateTableMonAn();
            }
        } else {
            this.themMonAnTableMonAn();
        }
        loadTableMonAn();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        if (this.table_monAn.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn món ăn!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int n = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa ?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (n == JOptionPane.NO_OPTION) {
            return;
        }
        int rowSelect = this.table_monAn.getSelectedRow();
        PhieuGoiMonDAO phieuGoiMonDao = new PhieuGoiMonDAO();
        PhieuGoiMon phieuGoiMon = new PhieuGoiMon(Integer.parseInt(this.table_monAn.getValueAt(rowSelect, 0).toString()), Integer.parseInt(this.maBan));
        if (!phieuGoiMonDao.xoaPhieuGoiMon(phieuGoiMon)) {
            JOptionPane.showMessageDialog(this, "Xóa thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
        this.btn_delete.setEnabled(false); 
        this.loadTableMonAn();
        if (!this.checkBanAnHasChecked(maBan)) {
            this.changeStateTable(false);
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datban1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datban1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datban1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datban1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datban1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_thanhToan;
    private javax.swing.JComboBox<String> cbo_monAn;
    private javax.swing.JPanel datban;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_chuaCoKhach;
    private javax.swing.JLabel label_daCoKhach;
    private javax.swing.JLabel label_date;
    private javax.swing.JLabel label_donGiaMonAn;
    private javax.swing.JLabel label_tenBan;
    private javax.swing.JTextField label_tenNhanVien;
    private javax.swing.JLabel label_thanhTien;
    private javax.swing.JLabel label_tienThua;
    private javax.swing.JLabel label_time;
    private javax.swing.JLabel label_tongTien;
    private javax.swing.JPanel panel_datBan;
    private javax.swing.JTable table_monAn;
    private javax.swing.JTextField txt_SoLuong;
    private javax.swing.JLabel txt_image;
    private javax.swing.JTextField txt_tienNhanCuaKhach;
    // End of variables declaration//GEN-END:variables
    
    public void setMaNV(String maNV) {
        this.maNV = maNV;
    }
    
    private void loadImageMonAn() {
        try {
            if (this.cbo_monAn.getSelectedIndex() == -1) { 
                return;
            }
            MonAn monAn = (MonAn) this.cbo_monAn.getSelectedItem();
            BufferedImage bufferedImage = ImageIO.read(new File("src/Image/" + monAn.getHinh()));
            Image image = bufferedImage.getScaledInstance(this.txt_image.getWidth(), this.txt_image.getHeight(), 1);
            txt_image.setIcon(new ImageIcon(image));
            this.label_donGiaMonAn.setText(NumberFormat.getInstance().format(monAn.getDonGia()) + " VNĐ");
        } catch (IOException ex) {
            Logger.getLogger(datban1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadCboMonAn() {
        try {
            MonAnDAO monAnDao = new MonAnDAO();
            ArrayList dsMonAn = monAnDao.loadMonAn();
            DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
            comboBoxModel.addAll(dsMonAn);

            cbo_monAn.setModel(comboBoxModel);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadBanAn() {
        try {
            BufferedImage bufferedImage;
            Image image;

            this.panel_datBan.setLayout(new GridLayout(3, 5, 2, 2));
            this.panel_datBan.setPreferredSize(new Dimension(470, 350));
            this.panel_datBan.setBackground(Color.black);

            BANANDAO banAnDao = new BANANDAO();
            ArrayList<BanAn> dsBanAn = banAnDao.loadBanAn();
            for (BanAn x : dsBanAn) {
                JPanel panel = new JPanel();
                panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));

                JButton btn_banAn = new JButton("");
                btn_banAn.setAlignmentX(JButton.CENTER_ALIGNMENT);

                btn_banAn.setCursor(new Cursor(Cursor.HAND_CURSOR)); 
                btn_banAn.setSize(60, 70);

                //TẠO ACTION LISTENER CHO BUTTON 
                btn_banAn.addActionListener(new ActionPerform(x.getMaBan(), x.getTenBan(), btn_banAn));
                //THAY ĐỔI TRANG THÁI CỦA BÀN THEO PHIẾU GỌI MÓN
                if (this.checkBanAnHasChecked(x.getMaBan())) {
                    bufferedImage = ImageIO.read(new File("src/Image/daCoKhach.png"));
                    image = bufferedImage.getScaledInstance(btn_banAn.getWidth() - 10, btn_banAn.getHeight() - 10, 1);
                    btn_banAn.setIcon(new ImageIcon(image));
                } else {
                    bufferedImage = ImageIO.read(new File("src/Image/chuaCoKhach.png"));
                    image = bufferedImage.getScaledInstance(btn_banAn.getWidth() - 10, btn_banAn.getHeight() - 10, 1);
                    btn_banAn.setIcon(new ImageIcon(image)); 
                }

                JLabel label_tenBan = new JLabel(x.getTenBan());
                label_tenBan.setAlignmentX(CENTER_ALIGNMENT);
                label_tenBan.setAlignmentY(CENTER_ALIGNMENT);
//                label_tenBan.setVerticalAlignment(JLabel.CENTER);
//                label_tenBan.setVerticalTextPosition(JLabel.CENTER);

                panel.add(btn_banAn);
                panel.add(label_tenBan);

                this.panel_datBan.add(panel);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadIcon() {
        try {
            this.btn_add.setBackground(Color.white);
            this.btn_thanhToan.setBackground(Color.white);
            BufferedImage bufferedImage;
            Image image;
            bufferedImage = ImageIO.read(new File("src/Image/chuaCoKhach.png"));
            image = bufferedImage.getScaledInstance(this.label_chuaCoKhach.getWidth(), this.label_chuaCoKhach.getHeight(), 1);
            this.label_chuaCoKhach.setIcon(new ImageIcon(image));

            bufferedImage = ImageIO.read(new File("src/Image/daCoKhach.png"));
            image = bufferedImage.getScaledInstance(this.label_daCoKhach.getWidth(), this.label_daCoKhach.getHeight(), 1);
            this.label_daCoKhach.setIcon(new ImageIcon(image));

            bufferedImage = ImageIO.read(new File("src/Image/add.png"));
            image = bufferedImage.getScaledInstance(this.btn_add.getWidth() - 10, this.btn_add.getHeight() - 10, 1);
            btn_add.setIcon(new ImageIcon(image));
            //btn_add.setHorizontalTextPosition(JButton.CENTER);

            bufferedImage = ImageIO.read(new File("src/Image/pay.png"));
            image = bufferedImage.getScaledInstance(this.btn_thanhToan.getWidth() - 10, this.btn_thanhToan.getHeight() - 10, 1);
            this.btn_thanhToan.setIcon(new ImageIcon(image));
            //this.btn_thanhToan.setHorizontalTextPosition(JButton.CENTER);

            bufferedImage = ImageIO.read(new File("src/Image/delete.png"));
            image = bufferedImage.getScaledInstance(this.btn_delete.getWidth() - 10, this.btn_delete.getHeight() - 10, 1);
            this.btn_delete.setIcon(new ImageIcon(image));
        } catch (IOException ex) {
            Logger.getLogger(datban1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadEnable(boolean b) {
        btn_add.setEnabled(b);
        btn_thanhToan.setEnabled(b);
        btn_delete.setEnabled(b);
    }

    private boolean checkEnableBtnAdd() {
        if (!this.txt_SoLuong.getText().isEmpty() && this.cbo_monAn.getSelectedIndex() != -1 && !this.label_tenBan.getText().isEmpty()) {
            return true;
        }
        return false; 
    }

    private boolean checkEnableBtnPay() {
        int rowCount = this.table_monAn.getRowCount();
        if (rowCount > 0 && this.tienNhan != 0) {
            return true;
        }
        return false;
    }

    private void loadTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SimpleDateFormat date = new SimpleDateFormat("dd/MM/yyyy");
                SimpleDateFormat time = new SimpleDateFormat("hh:mm:ss");
                Date d = new Date();
                label_date.setText(date.format(d));
                label_time.setText(time.format(d));
            }
        }).start();
    }

    private void loadTableMonAn() {
        try {
            
            this.tongTien = 0; 
            
            this.tableModel.setRowCount(0);
            ArrayList<PhieuGoiMon> dsPhieu = phieuGoiMonDao.getPhieuGoiMonByMaBan(this.maBan);
            for (PhieuGoiMon x : dsPhieu) {
                Vector<Object> vector = new Vector<>(); 
                vector.add(x.getMaMonAn());
                vector.add(x.getMaNhanVien());
                vector.add(x.getTenMonAn());
                vector.add(x.getSoLuong());
                vector.add(NumberFormat.getInstance().format(x.getDonGia()));
                this.tongTien += x.getSoLuong() * x.getDonGia();
                tableModel.addRow(vector);
            }

            this.table_monAn.updateUI();
            this.label_tongTien.setText(NumberFormat.getInstance().format(tongTien) + " VNĐ");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadCursor() {
        btn_add.setCursor(new Cursor(HAND_CURSOR));
        btn_thanhToan.setCursor(new Cursor(HAND_CURSOR));
        btn_delete.setCursor(new Cursor(HAND_CURSOR));
    }

    private int findFootQuantityInPhieuGoiMon() {
        //TÌM SỐ LƯỢNG MÓN ĂN MÀ BÀN ĐÓ ĐÃ GỌI (TÌM SỐ LƯỢNG MÓN ĂN ĐÓ TRONG PHIẾU GỌI MÓN)
        try {
            MonAn monAn = (MonAn) cbo_monAn.getSelectedItem();
            //PhieuGoiMonDao phieuGoiMonDao = new PhieuGoiMonDAO();
            PhieuGoiMon phieuGoiMon = new PhieuGoiMon();
            phieuGoiMon.setMaBan(Integer.parseInt(this.maBan));
            phieuGoiMon.setMaMonAn(monAn.getMaMonAn());
            return phieuGoiMonDao.findFootQuantityInPhieuGoiMon(phieuGoiMon);

        } catch (NumberFormatException e) {
            e.printStackTrace();
            return -1;
        }
    }

    private void capNhatThanhTien() {
        int soLuong = 0;
        MonAn monAn = (MonAn) cbo_monAn.getSelectedObjects()[0];
        if (!txt_SoLuong.getText().isEmpty()) {
            soLuong = Integer.parseInt(txt_SoLuong.getText());
        }
        double thanhTien = soLuong * monAn.getDonGia();
        label_thanhTien.setText(NumberFormat.getInstance().format(thanhTien) + " VNĐ");
    }

    private void updateTableMonAn() {
        
        try {
            MonAn monAn = (MonAn) cbo_monAn.getSelectedItem();
            int soLuongMonAn = this.findFootQuantityInPhieuGoiMon();
            PhieuGoiMon x = new PhieuGoiMon();
            x.setMaBan(Integer.parseInt(this.maBan));
            x.setMaNhanVien(this.maNV);
            x.setMaMonAn(monAn.getMaMonAn());
            x.setSoLuong(Integer.parseInt(txt_SoLuong.getText()) + soLuongMonAn);
            boolean n = phieuGoiMonDao.updatePhieuGoiMon(x);
            if (!n) {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (HeadlessException | NumberFormatException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    String maDB = "";
    private void themMonAnTableMonAn() {
        try {
            MonAn monAn = (MonAn) cbo_monAn.getSelectedItem();
            //PhieuGoiMonDao phieuGoiMonDao = new PhieuGoiMonDAO();
            PhieuGoiMon x = new PhieuGoiMon();
            x.setMaBan(Integer.parseInt(this.maBan));
            x.setMaNhanVien(this.maNV);
            x.setMaMonAn(monAn.getMaMonAn());
            x.setSoLuong(Integer.parseInt(txt_SoLuong.getText()));
            
            String tennv = label_tenNhanVien.getText();
            String maNV = NhanVienDAO.getNhanVienByMa(tennv);
            
            boolean n = phieuGoiMonDao.themPhieuGoiMon(x, maNV);

            if (n) {
                loadTableMonAn();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (HeadlessException | NumberFormatException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Thêm thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }

    private boolean checkBanAnHasChecked(String maBan) {
        //KIỂM TRA BÀN ĂN CÓ GỌI MÓN HAY CHƯA (KIỂM TRA PHIẾU GỌI MÓN)
        return phieuGoiMonDao.checkBanAnHasChecked(maBan);
    }

    private void changeStateTable(boolean b) {
        try {
            BufferedImage bufferedImage;
            if (b) {
                bufferedImage = ImageIO.read(new File("src/Image/daCoKhach.png"));
            } else {
                bufferedImage = ImageIO.read(new File("src/Image/chuaCoKhach.png"));
            }
            Image image = bufferedImage.getScaledInstance(50, 60, 1);
            this.buttonTrangThai.setIcon(new ImageIcon(image));
        } catch (IOException ex) {
            Logger.getLogger(datban1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private String getLastInsertMaHoaDon() {
        try {
            HOADONDAO hoaDonDao = new HOADONDAO();
            return hoaDonDao.getLastInsertMaHoaDon();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    private void createChiTietHoaDon(String maHoaDon) {
        try {
            CHITIETHOADONDAO chiTietHoaDonDao = new CHITIETHOADONDAO();
            chiTietHoaDonDao.themChiTietHoaDon(maHoaDon, this.maBan);
            this.loadTableMonAn();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadNhanVien() {
    NhanVienDAO nhanVienDao = new NhanVienDAO();
    String tenNhanVien = nhanVienDao.getNhanVienByMa(this.maNV);
    if (tenNhanVien != null) {
        this.label_tenNhanVien.setText(tenNhanVien);
    } else {
        this.label_tenNhanVien.setText("");
    }

}

    class ActionPerform implements ActionListener {

        String maBann, tenBan;
        JButton button;

        public ActionPerform(String maBan, String tenBan, JButton button) {
            this.maBann = maBan;
            this.tenBan = tenBan;
            this.button = button;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            buttonTrangThai = this.button;
            maBan = this.maBann;
            label_tenBan.setText(tenBan);  
            loadTableMonAn(); 
            if (checkEnableBtnAdd()) {
                btn_add.setEnabled(true);
            }
            if (checkEnableBtnPay()) {
                btn_thanhToan.setEnabled(true);
            }
        }
    }

    
}
